x-app-base: &app-base
  env_file: ./.env

services:
  postgis:
    <<: *app-base
    image: ghcr.io/baosystems/postgis:latest
    container_name: postgis
    ports:
      - '5432:5432'
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:

